const mongoose = require("mongoose");
const prefix = process.env.KODE_BAPAS || "Default";

const DataKlien = new mongoose.Schema(
  {
    RegisterUtama: {type: String, required: true, index:true},
    Nama: {type: String, required: true, index:true},
    LitmasTerselesaikan: String,
    TanggalPenyelesaianLitmas: String,
    NomorLitmas: String,
    TanggalSurat: String,
    TanggalPembagian: String,
    TanggalPenerimaanSurat: String,
    TanggalSurat2: String,
    TanggalPenerimaanSurat2: String,
    Perihal: String,
    NoRegisterLitmas: String,
    NoRegisterLitmas2: String,
    NoRegisterLitmas3: String,
    NoSuratPermintaan: String,
    NoSuratPermintaan2: String,
    JenisPermintaanLitmas: String,
    NamaInstansi: String,
    KelasInstansi: String,
    DaerahInstansi: String,
    Alamat: String,
    TempatLahir: String,
    TanggalLahir: String,
    Usia: String,
    JenisKelamin: String,
    Agama: String,
    Pendidikan: String,
    Pekerjaan: String,
    NamaPenjamin: String,
    AlamatPenjamin: String,
    DesaPenjamin: String,
    KecamatanPenjamin: String,
    DaerahPenjamin: String,
    NoTelpPenjamin: String,
    Katagori: String,
    Pasal: String,
    TanggalSuratKeputusanPengadilan: String,
    NoSuratKeputusanPengadilan: String,
    TanggalSuratKeputusanPengadilan2: String,
    NoSuratKeputusanPengadilan2: String,
    PidanaTahun: String,
    PidanaBulan: String,
    PidanaHari: String,
    RemisiTahun: String,
    RemisiBulan: String,
    RemisiHari: String,
    SubsiderTahun: String,
    SubsiderBulan: String,
    SubsiderHari: String,
    PertamaDitahan: String,
    SepertigaMasaPidana: String,
    SetengahMasaPidana: String,
    DuaPerTigaMasaPidana: String,
    BebasMurni: String,
    AnakDewasa: String,
    NamaPK: String,
    Jabatan: String,
    NIP: String,
    Golongan: String,
    Bulan: String,
    Tahun: String,
    InstansiPemintaLitmas: String,
    NamaLapas: String,
    StatusIntegrasiSaatIni: String,
    NomorSKIntegrasi: String,
    TanggalSKIntegrasi: String,
    NomorSuratPengantar: String,
    NomorBAST: String,
    NomorRegisterIntegrasi: String,
    MasaBimbinganSaatIniAwal: String,
    MasaBimbinganSaatIniAkhir: String,
    PetugasVerifikatorIntegrasi: String,
    WajibLapor: String,
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: `${prefix}User`,
      index: true
    }
    // --- PERBAIKAN: Hapus field yang tidak ada di CSV ---
    // KotaProperTrim: String,
    // TelatTidakPermintaanLitmas: String,
    // PetugasVerifikatorIntegrasi_2: String,
    // TanggalInputIntegrasi: String,
    // 
  },
  { collection: `${prefix}Klien` } // <-- pakai prefix dari ENV
);

module.exports = mongoose.model(`${prefix}Klien`, DataKlien);